services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_mind_backend
    image: go-mind-backend
    ports:
      - "8080:8080"
    volumes:
      - /var/www:/app/uploads
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://go_mind_db:3306/go_mind?serverTimezone=Europe/Moscow
      SPRING_DATASOURCE_USERNAME: go_mind_user
      SPRING_DATASOURCE_PASSWORD: rootpassword
      JAVA_OPTS: "-Xms4096m -Xmx4096m -XX:MaxMetaspaceSize=512m -Xss512k -XX:+UseG1GC -server"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: go_mind_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: go_mind
      MYSQL_USER: go_mind_user
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      # Добавляем кастомный конфиг в /etc/mysql/conf.d/custom.cnf
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
