services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_mind_backend
    image: go-mind-backend
    ports:
      - "8443:8443"
    volumes:
      - /var/www:/app/uploads
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://go_mind_db:3306/go_mind?serverTimezone=Europe/Moscow
      SPRING_DATASOURCE_USERNAME: go_mind_user
      SPRING_DATASOURCE_PASSWORD: rootpassword
      JAVA_OPTS: "-Xms1024m -Xmx2048m -XX:MaxMetaspaceSize=512m -Xss512k -XX:+UseG1GC -server -XX:ActiveProcessorCount=4"
    deploy:
      resources:
        limits:
          cpus: '2.0'
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: go_mind_db
    restart: always
    environment:
      MYSQL_DATABASE: go_mind
      MYSQL_USER: go_mind_user
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=64M --max_connections=1000

  frontend:
    build:
      context: ../gomind-landing
      dockerfile: Dockerfile
    container_name: go_mind_frontend
    image: go-mind-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  mysql_data:
